### ISSUE TITLE
Whether there should exists twitter icon beside the latest tweets?

### ISSUE THREAD

**Issue by huxuan** [luin/colortype#2]
RT

**Comment by luin** [comment]
我想过这个，这两天会通过Theme Options提供

**Comment by huxuan** [comment]
thx for quick response. I have clone it for huxuan.org!

**Comment by huxuan** [comment]
Fixed in commit 12f067610a8af52e3f7fd924eda6dc5f7b1849b2
Thx very much, @luin !
